#include "config.h"
#include <common/daemon.h>
#include <common/setup.h>
#include <stdio.h>

/* Intercept the log file writes, so a huge log message doesn't spam our
 * stdout, and so we can check what would have been written. */
static size_t last_fwrite_len;

#define fwrite test_fwrite
static size_t test_fwrite(const void *ptr, size_t size, size_t nmemb,
			  FILE *stream);

#include "../log.c"

static size_t test_fwrite(const void *ptr UNNEEDED, size_t size,
			  size_t nmemb, FILE *stream UNNEEDED)
{
	last_fwrite_len = size * nmemb;
	return nmemb;
}

void notify_log(struct lightningd *ld UNNEEDED,
		enum log_level level UNNEEDED,
		struct timeabs time UNNEEDED,
		const char *source UNNEEDED,
		const char *logmsg UNNEEDED)
{  }

void notify_warning(struct lightningd *ld UNNEEDED,
		    enum log_level level UNNEEDED,
		    struct timeabs time UNNEEDED,
		    const char *source UNNEEDED,
		    const char *logmsg UNNEEDED)
{  }

/* AUTOGENERATED MOCKS START */
/* Generated stub for command_check_done */
struct command_result *command_check_done(struct command *cmd)

{ fprintf(stderr, "command_check_done called!\n"); abort(); }
/* Generated stub for command_check_only */
bool command_check_only(const struct command *cmd UNNEEDED)
{ fprintf(stderr, "command_check_only called!\n"); abort(); }
/* Generated stub for command_deprecated_in_ok */
bool command_deprecated_in_ok(struct command *cmd UNNEEDED,
			      const char *param UNNEEDED,
			      const char *depr_start UNNEEDED,
			      const char *depr_end UNNEEDED)
{ fprintf(stderr, "command_deprecated_in_ok called!\n"); abort(); }
/* Generated stub for command_dev_apis */
bool command_dev_apis(const struct command *cmd UNNEEDED)
{ fprintf(stderr, "command_dev_apis called!\n"); abort(); }
/* Generated stub for command_fail */
struct command_result *command_fail(struct command *cmd UNNEEDED, enum jsonrpc_errcode code UNNEEDED,
				    const char *fmt UNNEEDED, ...)

{ fprintf(stderr, "command_fail called!\n"); abort(); }
/* Generated stub for command_filter_ptr */
struct json_filter **command_filter_ptr(struct command *cmd UNNEEDED)
{ fprintf(stderr, "command_filter_ptr called!\n"); abort(); }
/* Generated stub for command_log */
void command_log(struct command *cmd UNNEEDED, enum log_level level UNNEEDED,
		 const char *fmt UNNEEDED, ...)

{ fprintf(stderr, "command_log called!\n"); abort(); }
/* Generated stub for command_param_failed */
struct command_result *command_param_failed(void)

{ fprintf(stderr, "command_param_failed called!\n"); abort(); }
/* Generated stub for command_set_usage */
void command_set_usage(struct command *cmd UNNEEDED, const char *usage UNNEEDED)
{ fprintf(stderr, "command_set_usage called!\n"); abort(); }
/* Generated stub for command_success */
struct command_result *command_success(struct command *cmd UNNEEDED,
				       struct json_stream *response)

{ fprintf(stderr, "command_success called!\n"); abort(); }
/* Generated stub for command_usage_only */
bool command_usage_only(const struct command *cmd UNNEEDED)
{ fprintf(stderr, "command_usage_only called!\n"); abort(); }
/* Generated stub for json_stream_log_suppress_for_cmd */
void json_stream_log_suppress_for_cmd(struct json_stream *js UNNEEDED,
					    const struct command *cmd UNNEEDED)
{ fprintf(stderr, "json_stream_log_suppress_for_cmd called!\n"); abort(); }
/* Generated stub for json_stream_success */
struct json_stream *json_stream_success(struct command *cmd UNNEEDED)
{ fprintf(stderr, "json_stream_success called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

int main(int argc, char *argv[])
{
	struct log_book *lb;
	struct logger *l;
	char *huge;
	u8 *iodata;
	size_t off;
	const u8 *io;
	const char *msg;
	struct log_hdr lhdr;
	const size_t max = sizeof(((struct log_book *)0)->ringbuf) / 64;

	common_setup(argv[0]);

	lb = new_log_book(NULL);
	/* Print everything, so we exercise log_to_files() too. */
	assert(opt_log_level("debug", lb) == NULL);
	l = new_logger(lb, lb, NULL, "test %s", "prefix");

	huge = malloc(max + 2);

	/* Exactly at the cap_header() limit: not truncated. */
	memset(huge, 'x', max);
	huge[max] = '\0';
	log_debug(l, "%s", huge);
	assert(last_fwrite_len > max);

	/* One byte over: cap_header() replaces it with tal memory, which
	 * logv() used to hand to free().  Also too long for the stack
	 * buffer in log_to_files(), which used to be an unbounded VLA. */
	memset(huge, 'x', max + 1);
	huge[max + 1] = '\0';
	log_debug(l, "%s", huge);
	assert(last_fwrite_len > max + 1);

	/* log_io() promises TAKES on both args: if it doesn't consume them,
	 * common_shutdown() below complains about the outstanding take(). */
	iodata = tal_arr(NULL, u8, 4);
	memset(iodata, 7, 4);
	log_io(l, LOG_IO_IN, NULL, take(tal_strdup(NULL, "hello")),
	       take(iodata), 4);

	/* Same, but long enough that cap_header() truncates it: log_io()
	 * used to lose the original pointer, so taken() never matched. */
	iodata = tal_arr(NULL, u8, 4);
	memset(iodata, 7, 4);
	log_io(l, LOG_IO_IN, NULL, take(tal_strdup(NULL, huge)),
	       take(iodata), 4);
	free(huge);

	/* Far larger than any sane stack: log_to_files() used to size a VLA
	 * off the message length, so this overflowed the stack. */
	huge = malloc(16 * 1024 * 1024 + 1);
	memset(huge, 'v', 16 * 1024 * 1024);
	huge[16 * 1024 * 1024] = '\0';
	log_debug(l, "%s", huge);
	free(huge);

	off = 0;
	assert(get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));
	assert(lhdr.level == LOG_DBG);
	assert(lhdr.msglen == max);
	assert(lhdr.iolen == 0);
	assert(strncmp(msg, "xxxx", 4) == 0);

	assert(get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));
	assert(lhdr.level == LOG_DBG);
	assert(strstarts(msg, "[TRUNCATED message from "));

	assert(get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));
	assert(lhdr.level == LOG_IO_IN);
	assert(lhdr.msglen == strlen("hello"));
	assert(strncmp(msg, "hello", strlen("hello")) == 0);
	assert(lhdr.iolen == 4);

	assert(get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));
	assert(lhdr.level == LOG_IO_IN);
	assert(strstarts(msg, "[TRUNCATED message from "));

	assert(get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));
	assert(lhdr.level == LOG_DBG);
	assert(strstarts(msg, "[TRUNCATED message from "));

	assert(!get_log_entry(tmpctx, lb, &lhdr, &msg, &io, &off));

	tal_free(l);
	common_shutdown();
}
